/// Firebase 프로젝트별 플랫폼 옵션을 담은 자동 생성 파일이다.
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBdOucwpM_fsaWyL8Y7s6wLQxa1lHbyM',
    appId: '1:118577179246:android:726a7b5abe5a5a3e9d947f',
    messagingSenderId: '118577179246',
    projectId: 'jgbusiness-147a8',
    storageBucket: 'jgbusiness-147a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVX5NV1W1P_4pSMg57zrzNwov5MDai9EE',
    appId: '1:118577179246:ios:a4b18aef01ad6ecc9d947f',
    messagingSenderId: '118577179246',
    projectId: 'jgbusiness-147a8',
    storageBucket: 'jgbusiness-147a8.firebasestorage.app',
    iosBundleId: 'com.wonjongseo.jgBusiness',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF5DCKDkUkKq-05gP4y3fCbJQvk272QHk',
    appId: '1:118577179246:web:be5f80b8390a3b9a9d947f',
    messagingSenderId: '118577179246',
    projectId: 'jgbusiness-147a8',
    authDomain: 'jgbusiness-147a8.firebaseapp.com',
    storageBucket: 'jgbusiness-147a8.firebasestorage.app',
    measurementId: 'G-PXMPSX6T7B',
  );

}